### ISSUE TITLE
Namespace troubles

### ISSUE THREAD

**Issue by jpmikkers** [Epictek/Avalonia-Blazor-Bindings#1]
Problem description:
Compiling and running the demo project works, but in visual studio v17.11.5, when I open the Sample MainPage.razor I get the following warnings on every avalonia component : `RZ10012: Found markup element with unexpected name 'Window'. If this is intended to be a component, add a @using directive for its namespace.`

This also means inside the razor editor there's no intellisense for properties like Width Height HorizontalAlignment etc.

Then I thought: maybe I have to regenerate the Blazor wrappers. This results in generated files that refer to the namespace Avalonia.Controls directly instead of AC , and the compiler does not understand it's referring to 'native' avalonia here instead of BlazorBindings.Avalonia.

**Comment by jpmikkers** [comment]
I forked the warappa newest branch, then all I did was bump the avalonia version.. same RZ10012 issue happened for me. Deleting the bin obj .vs folders didn't help 😒 . The Razor language server is just .. confused ..
Reverting to Avalonia 11.0.9 then deleting .vs bin obj folders fixes it! Something in Avalonia 11.1.4 is poisoning the well.

**Comment by Epictek** [comment]
> I forked the warappa newest branch, then all I did was bump the avalonia version.. same RZ10012 issue happened for me. Deleting the bin obj .vs folders didn't help 😒 . The Razor language server is just .. confused .. Reverting to Avalonia 11.0.9 then deleting .vs bin obj folders fixes it! Something in Avalonia 11.1.4 is poisoning the well.

Have you tried putting  `@using BlazorBindings.Avalonia.Elements` in my razor page.
Could also try `@using Window = BlazorBindings.Avalonia.Elements.Window`

Seems like it could be an issue with the `_imports.razor`

**Comment by Epictek** [comment]
More investigation, can only reproduce in VS, Works fine in Rider

**Comment by jpmikkers** [comment]
Similarly, editing the .razor in vscode has no trouble identifying and giving intellisense for the components. Sooo waiting for a better Visual Studio then :(

**Comment by Epictek** [comment]
Reopening as I want to investigate this issue more

**Comment by Epictek** [comment]
@jpmikkers made some changes, now using the "BlazorBindingsAvalonia" namespace and it seems to have resolved the issues with visual studio for me so it was definitely a namespace issue (I really hate how .NET handles namespaces). Could you give the latest master code a test 😊

**Comment by jpmikkers** [comment]
that works! vs razor editor is no longer confused 🥳 (I should look up how namespace resolving _actually_ works). Btw, Directory.Packages.prop has some duplicate entries now, causes warnings while compiling.

**Comment by Epictek** [comment]
> that works! vs razor editor is no longer confused 🥳 (I should look up how namespace resolving _actually_ works). Btw, Directory.Packages.prop has some duplicate entries now, causes warnings while compiling.
> 

Glad it's resolved. I'll close this issue
